### ISSUE TITLE
Checklist do MVP

### ISSUE THREAD

**Issue by rodrigomuniz** [vtex/design.vtex.com#1]
- [x] Instalar, configurar e testar o pink
- [x] Apontar subdomínio para ghpages
- [x] Instalar Google Analytics
- [x] Publicar página inicial (com gráfico circular irado com o processo, frase com nosso propósito e CTA para a vaga)
- [ ] Publicar post no vtexdesign.tumblr.com

---

- [x] section e header do tumblr (making of) [muniz]
- [x] revisar espaçamentos em geral (mobile e desktop) [muniz e zeh]
- [ ] ~~bug do teal na transição da cor do gráfico [zeh]~~ #8

**Comment by rodrigomuniz** [comment]
@amoreira Consegue ajudar os desenhistas com o segundo item da lista? 😅
https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by bernardolemgruber** [comment]
Falta o gráfico circular ~irado~ mas considerei válido, anyway. Vou tentar melhorar essa parte hoje.

**Comment by dfosco** [comment]
Nem sei se vale criar uma issue pra isso de tão pequeno, mas no meu browser o CTA tá colado no fundo do viewport — vale um padding lá pra respirar 💨

![image](https://cloud.githubusercontent.com/assets/3229933/15836081/7f500e14-2c09-11e6-880d-656e1a67e5b4.png)

**Comment by rodrigomuniz** [comment]
@bernardolemgruber migo, vou reabrir a task lá de cima de publicar a página, pq acho que o valor mínimo não foi alcançado ainda. Acho que o valor mínimo não pode ser só pra gente (hoje o valor é focado na gente ter qualquer coisa no ar). Deveria ser o valor mínimo para quem for entrar na página. Por isso acho que o gráfico deveria ser melhor trabalhado e ter mais destaque que a frase. _Just saying..._ 😗
